version: '3'
services:
    db:
        image: postgres:12.8
        environment:
            POSTGRES_PASSWORD: enviu_dev
            POSTGRES_USER: postgres
        network_mode: host
    blockscout:
        image: surfingnerd/blockscout:v0.8-372
        depends_on:
            - "db"
        ports:
            - "4000:4000"
        tty: true
        network_mode: host
        environment:
            ETHEREUM_JSONRPC_HTTP_URL: http://172.0.0.1:8545
            ETHEREUM_JSONRPC_TRACE_URL: http://172.0.0.1:8545
            ETHEREUM_JSONRPC_WS_URL: ws://172.0.0.1:8545
            ETHEREUM_JSONRPC_VARIANT: geth
            HOST: 127.0.0.1
            DATABASE_URL: postgresql://postgres:@127.0.0.1:5432/explorer?ssl=false

